#!/bin/sh
# apache-entry: optionally wire a tenant-supplied Apache config directory
# (APACHE_CONF_DIR) into the main server config, then exec httpd.
#
# Mirrors static-nginx's NGINX_CONF_DIR entrypoint (worker-entry.go). Apache's
# base image has a shell, so this is a plain script rather than a Go binary.
#
# Unset/empty -> remove any stale glue and start with the default config.
# Set to <dir> -> create <dir>, seed its README if missing, and write a glue
# file (picked up by `IncludeOptional conf/user-include/*.conf` in httpd.conf)
# that includes <dir>/*.conf. If <dir> lives under the web root, the glue also
# refuses to serve it so tenant config is never publicly downloadable.
set -eu

DOC_ROOT='/usr/local/apache2/htdocs'
GLUE_DIR='/usr/local/apache2/conf/user-include'
GLUE_FILE="${GLUE_DIR}/00-user-config.conf"
README_SRC='/usr/local/share/apache-config-readme.txt'
RUNTIME_USER='webuser'

log() { printf '[apache-entry] %s\n' "$*" >&2; }

# Collapse duplicate slashes and strip a trailing slash (keeping bare "/").
normalize_path() {
  printf '%s' "$1" | sed -e 's://*:/:g' -e 's:\(.\)/$:\1:'
}

setup_user_config() {
  dir=$(printf '%s' "${APACHE_CONF_DIR:-}" | tr -d '[:space:]')

  if [ -z "$dir" ]; then
    # Feature off: ensure no leftover include from a previous config.
    rm -f "$GLUE_FILE"
    return 0
  fi

  dir=$(normalize_path "$dir")

  case "$dir" in
    /*) ;;
    *)
      log "APACHE_CONF_DIR must be an absolute path (got '$dir'); ignoring"
      rm -f "$GLUE_FILE"
      return 0
      ;;
  esac
  case "$dir" in
    *..*)
      log "APACHE_CONF_DIR must not contain '..' (got '$dir'); ignoring"
      rm -f "$GLUE_FILE"
      return 0
      ;;
  esac
  if [ "$dir" = "$DOC_ROOT" ]; then
    log "APACHE_CONF_DIR must not be the web root ($DOC_ROOT); ignoring"
    rm -f "$GLUE_FILE"
    return 0
  fi

  if ! mkdir -p "$dir" 2>/dev/null; then
    log "cannot create APACHE_CONF_DIR $dir; ignoring"
    rm -f "$GLUE_FILE"
    return 0
  fi
  # Match the runtime user httpd drops its children to, so the directory is
  # readable by the server and writable by the tenant's file tools.
  chown "$RUNTIME_USER:$RUNTIME_USER" "$dir" 2>/dev/null || true

  # Seed the README if the tenant hasn't added one — never clobber.
  if [ ! -e "$dir/README.txt" ] && [ -f "$README_SRC" ]; then
    if cp "$README_SRC" "$dir/README.txt" 2>/dev/null; then
      chown "$RUNTIME_USER:$RUNTIME_USER" "$dir/README.txt" 2>/dev/null || true
      log "seeded $dir/README.txt"
    else
      log "README seed failed for $dir"
    fi
  fi

  mkdir -p "$GLUE_DIR"
  {
    printf '# Generated by apache-entry from APACHE_CONF_DIR=%s — do not edit.\n' "$dir"
    printf 'IncludeOptional "%s/*.conf"\n' "$dir"
    # The deny block is emitted AFTER the include so that it wins over any
    # <Directory> the tenant declares for the same path (last match wins).
    case "$dir" in
      "$DOC_ROOT"/*)
        printf '<Directory "%s">\n' "$dir"
        printf '    AllowOverride None\n'
        printf '    Require all denied\n'
        printf '</Directory>\n'
        ;;
    esac
  } > "$GLUE_FILE"

  # A typo in a tenant .conf would otherwise crash-loop the pod. Validate, and
  # on failure drop the glue so the site keeps serving with the default config
  # — the reason is printed above for the tenant to find in the workload logs.
  if ! httpd -t 2>/tmp/apache-conf-test.err; then
    log "APACHE_CONF_DIR=$dir contains an invalid configuration — IGNORING it and"
    log "starting with the default config. Fix the file(s) and restart. Apache said:"
    sed 's/^/[apache-entry]   /' /tmp/apache-conf-test.err >&2 || true
    rm -f "$GLUE_FILE" /tmp/apache-conf-test.err
    return 0
  fi
  rm -f /tmp/apache-conf-test.err
  log "APACHE_CONF_DIR=$dir wired into the server config"
}

setup_user_config
exec "$@"
